### ISSUE TITLE
Running the repl in the background

### ISSUE THREAD

**Issue by Sgoettschkes** [lemmings-io/clojure#2]
I'm trying to get the repl running in the background with the goal of adding some kind of startup script which does this automatically. This would mean that after doing a `vagrant up`, one could connect to the repl without additional steps needed.

My first approach was to run the repl command like this: 

`lein repl :headless :host 0.0.0.0 :port 7888 &`

It seems to work but I can't connect from Atom. This however does work:

`lein repl :headless :host 0.0.0.0 :port 7888 < /dev/null &`

I guess this is not the right way to create a daemon but got stuck on it for now.

Any implementation ideas and or thoughts on this?

**Comment by davidmann4** [comment]
I guess you could create a custom service so you can do 

service lemmings start
service lemmings status
service lemmings stop

and so on ...

https://www.scalescale.com/tips/nginx/create-linux-daemon-service/#

**Comment by Sgoettschkes** [comment]
The Vagrant setup uses a Ubuntu 16.04 box which runs systemd I assume, so creating what is called a "Unit" (as far as I understood) for systemd could do the trick: https://patrakov.blogspot.co.at/2011/01/writing-systemd-service-files.html

**Comment by Sgoettschkes** [comment]
@tosh @allanberger I got a working systemd service and have prepared the code. I'd rather push a branch to this repo than to fork but have no write permission. No idea if this is intentional and you'd like me to fork or just a permissions problem!

**Comment by davidmann4** [comment]
PR!
